version: '3.9'
  
services:

 munin:
    image: aheimsbakk/munin-alpine    
    container_name: munin-server
    restart: always
    ports:
      - "99:80"
    privileged: true
    volumes:
      - ./munin/munin-conf.d:/etc/munin/munin-conf.d
      - ./munin/munin.conf:/etc/munin/munin.conf
      - ./munin/plugin-conf.d:/etc/munin/plugin-conf.d
      - ./munin/plugins/:/etc/munin/plugins/  
      - ./lib/munin:/var/lib/munin
      - ./log/munin:/var/log/munin
